# Generated by Django 4.1.6 on 2023-02-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0002_alter_uuidforwebinar_path_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uuidforwebinar',
            name='path_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
