# Generated by Django 4.1.6 on 2023-02-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0003_alter_uuidforwebinar_path_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uuidforwebinar',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='uuidforwebinar',
            name='path_link',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uuidforwebinar',
            name='uuid',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
