# Generated by Django 4.1.6 on 2023-02-14 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0003_alter_uuidforwebinar_path_link'),
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='webinar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='webinar.webinar'),
            preserve_default=False,
        ),
    ]
